// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqDKqZ2i3nQ5zrMxlpNGNQqoJdpwXGa4w',
    appId: '1:482211253911:web:32ffb7a3bf5df9e17ea3d2',
    messagingSenderId: '482211253911',
    projectId: 'workshopp',
    authDomain: 'workshopp.firebaseapp.com',
    storageBucket: 'workshopp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcSu8w6BpMqjmB0oa6vUJiDj5TwPn73Yg',
    appId: '1:482211253911:android:1341c88318066b6e7ea3d2',
    messagingSenderId: '482211253911',
    projectId: 'workshopp',
    storageBucket: 'workshopp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9BvnCIXGaovUl0tYnTR2rA57aiqQ0CGA',
    appId: '1:482211253911:ios:1153545038e4593b7ea3d2',
    messagingSenderId: '482211253911',
    projectId: 'workshopp',
    storageBucket: 'workshopp.appspot.com',
    iosBundleId: 'com.example.workshop2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9BvnCIXGaovUl0tYnTR2rA57aiqQ0CGA',
    appId: '1:482211253911:ios:1153545038e4593b7ea3d2',
    messagingSenderId: '482211253911',
    projectId: 'workshopp',
    storageBucket: 'workshopp.appspot.com',
    iosBundleId: 'com.example.workshop2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqDKqZ2i3nQ5zrMxlpNGNQqoJdpwXGa4w',
    appId: '1:482211253911:web:b1d6a48159b24db37ea3d2',
    messagingSenderId: '482211253911',
    projectId: 'workshopp',
    authDomain: 'workshopp.firebaseapp.com',
    storageBucket: 'workshopp.appspot.com',
  );
}
